apiVersion: apps/v1
kind: Deployment
metadata:
  name: filter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filter
  template:
    metadata:
      labels:
        app: filter
    spec:
      containers:
        - name: filter
          image: wcygan/counter-filter:latest
          ports:
            - containerPort: 8001
