apiVersion: apps/v1
kind: Deployment
metadata:
  name: beam-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beam-job
  template:
    metadata:
      labels:
        app: beam-job
    spec:
      containers:
        - name: beam-job
          image: wcygan/counter-beam-job:latest